# Generated by Django 4.0.2 on 2022-03-05 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator('enter a valid Email')])),
            ],
        ),
        migrations.CreateModel(
            name='Students_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_semester', models.CharField(max_length=30)),
                ('registration_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2030), django.core.validators.MinValueValidator(1990)])),
                ('phone', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('students_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainControl.students')),
            ],
        ),
    ]
