# Generated by Django 4.0.2 on 2022-03-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainControl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_information',
            name='students_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='mainControl.students'),
        ),
    ]
